name: Run units tests and create release
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: "3.8"

      install_script:
        type: string
        required: false
        default: ""

    secrets:
      REPOSITORY_USER_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip pytest
          pip install -r requirements.txt

      - name: Execute install script
        if: ${{ inputs.install_script }} != ""
        run: ${{ inputs.install_script }}

      - name: Run tests with pytest
        run: pytest -x
