name: Run units tests and create release
on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: "3.8"

    secrets:
      REPOSITORY_USER_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run tests with pytest
        run: pytest -x
