name: Run units tests and create release
on:
  workflow_call:
    inputs:
      skip_pytest:
        type: boolean
        required: false
        default: false
        
      python_version:
        type: string
        required: false
        default: "3.8"

      install_script:
        type: string
        required: false
        default: ""

      copy_spot_library:
        type: boolean
        required: false
        default: false

      spot_library_path:
        type: string
        required: false
        default: "."

      use_lfs:
        type: boolean
        required: false
        default: false

    secrets:
      REPOSITORY_USER_TOKEN:
        required: true

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.use_lfs }}

      - name: Checkout LFS objects if needed
        if: ${{ inputs.use_lfs }}
        run: git lfs checkout
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip pytest
          pip install -r requirements.txt

      - name: Copy Spot Library
        if: ${{ inputs.copy_spot_library }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_USER_TOKEN }}
        run: |
          rm ${{ inputs.spot_library_path }}/spot_levatas_client-1.0-py3-none-any.whl
          gh release download -R vinsa-ai/spot-levatas-client -p *.whl -D ${{ inputs.spot_library_path }}/
          pip install ${{ inputs.spot_library_path }}/spot_levatas_client-1.0-py3-none-any.whl

      - name: Execute install script
        if: ${{ inputs.install_script }} != ""
        env: DEFINITELY_DOING_PYTEST: 1
        run: ${{ inputs.install_script }}

      - name: Run tests with pytest
        if: ${{ ! inputs.skip_pytest }}
        run: pytest -x
        
      - name: Warning about pytest
        if: ${{ inputs.skip_pytest }}
        run: |
          echo '::warning:: pytest is disabled.'
